package com.xiaomo.TimeMachine.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setNickName(String nickName) {
		set("nick_name", nickName);
	}

	public String getNickName() {
		return get("nick_name");
	}

	public void setPassword(String password) {
		set("password", password);
	}

	public String getPassword() {
		return get("password");
	}

	public void setEmail(String email) {
		set("email", email);
	}

	public String getEmail() {
		return get("email");
	}

	public void setEmailVerify(Integer emailVerify) {
		set("email_verify", emailVerify);
	}

	public Integer getEmailVerify() {
		return get("email_verify");
	}

	public void setHeadPhoto(String headPhoto) {
		set("head_photo", headPhoto);
	}

	public String getHeadPhoto() {
		return get("head_photo");
	}

	public void setSex(Integer sex) {
		set("sex", sex);
	}

	public Integer getSex() {
		return get("sex");
	}

	public void setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
	}

	public java.util.Date getBirthday() {
		return get("birthday");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return get("status");
	}

	public void setLastLoginTime(java.util.Date lastLoginTime) {
		set("last_login_time", lastLoginTime);
	}

	public java.util.Date getLastLoginTime() {
		return get("last_login_time");
	}

	public void setSignature(String signature) {
		set("signature", signature);
	}

	public String getSignature() {
		return get("signature");
	}

	public void setUrl(String url) {
		set("url", url);
	}

	public String getUrl() {
		return get("url");
	}

	public void setLiveness(Integer liveness) {
		set("liveness", liveness);
	}

	public Integer getLiveness() {
		return get("liveness");
	}

	public void setContribution(Integer contribution) {
		set("contribution", contribution);
	}

	public Integer getContribution() {
		return get("contribution");
	}

	public void setAuthority(Integer authority) {
		set("authority", authority);
	}

	public Integer getAuthority() {
		return get("authority");
	}

	public void setDelStatus(Integer delStatus) {
		set("del_status", delStatus);
	}

	public Integer getDelStatus() {
		return get("del_status");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
